### ISSUE TITLE
Error: Cannot find module './normalized-options'

### ISSUE THREAD

**Issue by friederbluemle** [brodybits/create-react-native-module#12]
I just installed this command line tool:

```
yarn global add create-react-native-module
```

Everything seems fine.

However, trying to execute any command fails:

```
$ create-react-native-module -V
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module './normalized-options'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/create-react-native-module/command.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
```

**Comment by zfoltin** [comment]
I guess it's because `normalized-options.js` seems to be missing from https://github.com/brodybits/create-react-native-module/blob/dev/package.json#L28 ?

**Comment by brodybits** [comment]
Thanks guys, should be fixed on npm now. I just raised #14 to avoid this kind of an issue in the future.
