### ISSUE TITLE
Not able to generate example project

### ISSUE THREAD

**Issue by sharma-archu** [brodybits/create-react-native-module#236]
I am using below mentioned command to generate the example project:

> create-react-native-module --package-identifier io.gpstracking --generate-example GPSTracking

But getting following errors::

```
[CREATE new React Native module with the following options:

  root moduleName: react-native-gps-tracking
  name: GPSTracking
  prefix: 
  modulePrefix: react-native
  packageIdentifier: io.gpstracking
  platforms: ios,android
  tvosEnabled: false
  githubAccount: github_account
  authorName: Your Name
  authorEmail: yourname@email.com
  license: MIT
  view: false
  useAppleNetworking: false
  generateExample: true
  exampleName: example
  writeExamplePodfile: false
  
CREATE: Check for valid react-native-cli tool version, as needed to generate the example project
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
react-native --version ok
CREATE: Check for valid Yarn CLI tool version, as needed to generate the example project
/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/lib/lib.js:142
      throw new Error(
      ^

Error: yarn --version failed; both react-native-cli and yarn CLI tools are needed to generate example project
    at generateWithNormalizedOptions (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/lib/lib.js:142:13)
    at lib (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/lib/lib.js:262:10)
    at Object.func (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/lib/cli-command.js:45:12)
    at Command.runAction (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/lib/cli-program.js:14:13)
    at Command.listener (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/node_modules/commander/index.js:674:12)
    at Command.parse (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/Users/Iron/.nvm/versions/node/v12.13.1/lib/node_modules/create-react-native-module/lib/cli-program.js:29:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
```

What can I do to generate native module with example??

**Comment by brodybits** [comment]
You need to install Yarn for this tool to generate the example. This should already be explained by the error message that was posted in this issue.
