### ISSUE TITLE
yarn test fail in example folder

### ISSUE THREAD

**Issue by ElieSol** [brodybits/create-react-native-module#364]
Hello !

I tried creating a library with an example folder in it using the command 
```
create-react-native-module --generate-example TestLibrary
```
then followed _create-react-native-module_ documentation, everything is working great except when I try to run the command ```yarn test``` in the example folder... I get the following error: 
```
yarn run v1.22.4
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

      1 | import { NativeModules } from 'react-native';
      2 | 
    > 3 | const { TestModule } = NativeModules;
        |                        ^
      4 | 
      5 | export default TestModule;
      6 | 

      at invariant (../node_modules/invariant/invariant.js:40:15)
      at Object.<anonymous> (../node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:166:3)
      at Object.NativeModules (../node_modules/react-native/Libraries/react-native/react-native-implementation.js:323:12)
      at Object.<anonymous> (../index.js:3:24)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.74 s
Ran all test suites.
error Command failed with exit code 1.
```
I don't know if this issue is due to my configurations (i.e. react-native version etc..) or if I missed some steps...

Thank you in advance for your help :)

**Comment by brodybits** [comment]
My apologies for the delay. This has never been tested or supported, needs to be documented.

I would love to get this working (someday). Thanks for reporting.
