### ISSUE TITLE
Drop support for Node.js pre-8.0

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#37]
__updated April 2020:__

- [x] add engines field to specify minimum Node.js version 8
- ~~start using a feature such as `util.promisify()` that is not supported on older Node.js versions (see <https://2ality.com/2017/05/util-promisify.html>)~~ _(not needed since the recent `update-notifier ` package version already fails on Node.js 6)_
- [x] _update the minimum Node.js version requirement in the documentation_
- [x] _highly desired: use a utility such as `please-upgrade-node` to explicitly check the Node.js engine version and exit with a descriptive message in case it does not match_

Older Node.js versions are no longer updated and should not be considered secure.

P.S. The **bug** label is added since this utility is not actively tested with Node.js pre-8.0.

P.S. 2: When I tried this package on Node.js 6, it failed with the following error message:

```
/Users/brodybits/dev/nvs/node/6.17.1/x64/lib/node_modules/create-react-native-module/node_modules/update-notifier/index.js:74
			(async () => {
			       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brodybits/dev/nvs/node/6.17.1/x64/lib/node_modules/create-react-native-module/cli.js:4:24)
```

The task list above is updated.

**Comment by brodybits** [comment]
> * add engines field to specify minimum Node.js version 8

done in 291903b0 (PR #295)

> * update the minimum Node.js version requirement in the documentation

done in 00f6feade25453694d7d6a45692c5671202bbb60 (back in July 2019)

> * highly desired: use a utility such as `please-upgrade-node` to explicitly check the Node.js engine version and exit with a descriptive message in case it does not match

done in 291903b0 (PR #295)

PR #295 is already merged into master, for 0.17.0 release coming in the near future.
