### ISSUE TITLE
Ugly CLI exception if no command arguments are present

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#48]
If I would just do the following command on the command line, with no arguments:

    create-react-native-module

it shows an ugly exception message like this:

```
/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/lib/normalized-options.js:18
    throw new Error('Please write your library\'s name');
    ^

Error: Please write your library's name
    at module.exports (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/lib/normalized-options.js:18:11)
    at Object.func (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/lib/cli-command.js:47:27)
    at Command.runAction (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/cli.js:16:13)
    at Command.listener (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/node_modules/commander/index.js:315:8)
    at emitNone (events.js:106:13)
    at Command.emit (events.js:208:7)
    at Command.parseArgs (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/node_modules/commander/index.js:665:12)
    at Command.parse (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/brodybits/dev/nvs/node/8.16.0/x64/lib/node_modules/create-react-native-module/cli.js:27:9)
    at Module._compile (module.js:653:30)
```

I think it should show the usage help instead.

**Comment by brodybits** [comment]
and the following commands result in an "unknown option" error message:

* `create-react-native-module --asd`
* `create-react-native-module --asd aa`

Consistent CLI error handling would be better.

Consistent CLI error handling may need some help from `commander`. Using recent `3.0.1` version of `commander` does not seem to change this behavior.
