### ISSUE TITLE
metro bundler fails with example

### ISSUE THREAD

**Issue by drisme** [brodybits/create-react-native-module#75]
Hi, I've been trying to solve the following error but no luck so far:

> bundling failed: Error: Unable to resolve module `react-native-yada` from `/Volumes/Personals/workspace/react-native-yada/example/App.js`: Module `react-native-yada` does not exist in the Haste module map

This is my first attempt at creating a native module. I've also been trying to figure out ways to accelerate the dev process. Upon creating this module I found that the example app was set up with a copy of the dependency rather than a symlink so decided to npm link the dep instead.

It working for a hot moment, but so far I haven't gotten hot reloading to work yet, and I couldn't find any good articles on how to increase my cycle speed. So far I've always had to exit and rerun react-native run-ios.

An advice or pointers would be greatly appreciated. Thx!

**Comment by brodybits** [comment]
Please show the contents of your example `package.json` and `yarn.lock` files.

**Comment by drisme** [comment]
Hi, so I tried building the project from scratch again, using the cocoaPods option and doing the pod install in the ios subdirectory. Now I get a different error, which I believe is related to swift 5? I tried install Xcode 10.2 but to no avail. Even the alleged 10.1 to 10.2 hack didn't work for me. Here's the stack trace:

```
info Building (using "xcodebuild -workspace SoundStationExample.xcworkspace -configuration Debug -scheme SoundStationExample -destination id=19F0463E-CF52-47DC-ADD2-A422FB2DFBAF -derivedDataPath build/SoundStationExample")
...................
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening SoundStationExample.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Volumes/Personals/workspace/sound-station/example/ios/build/SoundStationExample

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'sound-station')

Build system information
warning: The iOS Simulator deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'SwiftLint')

Build system information
warning: The iOS Simulator deployment target is set to 12.4, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'SoundStationExampleTests')

Build system information
warning: Capabilities for SoundStationExample may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'SoundStationExample')


2019-09-02 22:18:26.828 XCBBuildService[2879:25282] Failed to remove: /Volumes/Personals/workspace/sound-station/example/ios/build/SoundStationExample/Build/Intermediates.noindex/XCBuildData/56b32765ec89a244a605f3ea845a044a-desc.xcbuild: No such file or directory (2)
** BUILD FAILED **
```

**Comment by drisme** [comment]
Ok, I managed to fix this installing the Swift 5 package for command line tools (I'm running Xcode 10.1 on High Sierra) now it's back to the old error:
```

Looking for JS files in
   /Volumes/Personals/workspace/sound-station/example
   /Volumes/Personals/workspace/sound-station 

Loading dependency graph...jest-haste-map: Haste module naming collision: hermes-inspector-msggen
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json
    * <rootDir>/../node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Volumes/Personals/workspace/sound-station/example/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Volumes/Personals/workspace/sound-station/example/node_modules/jest-haste-map/build/index.js:691:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 3030) {
  mockPath1: 'node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json',
  mockPath2: '../node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json'
}
(node:13123) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Volumes/Personals/workspace/sound-station/example/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Volumes/Personals/workspace/sound-station/example/node_modules/jest-haste-map/build/index.js:691:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 3030)
(node:13123) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13123) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by drisme** [comment]
```
{
  "name": "SoundStationExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "preinstall": "cd .. && npm i && npm run build",
    "postinstall": "npm run build",
    "build": "rm -rf build && ../node_modules/.bin/tsc -p ./src",
    "lint": "../node_modules/.bin/tslint -p ./src",
    "watch": "npm run build -- -w",
    "reset:packager": "watchman watch-del-all && react-native start --reset-cache",
    "run:android": "react-native run-android --no-jetifier",
    "clean:android": "cd android && ./gradlew clean",
    "install:pods": "cd ios && which pod && pod install || echo '\\033[1;33m Warning: cocoapods not found!\\033[0m'",
    "generate:android:signing-key": "keytool -genkey -v -keystore example.keystore -alias example -keyalg RSA -keysize 2048 -validity 10000 && mv example.keystore android/app",
    "generate:android:apk": "npm run generate:android:bundle && cd android && ./gradlew assembleRelease",
    "generate:android:bundle": "npm run build && react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle",
    "build:docker:image": "docker build -t sound-station-example.image -f ./Dockerfile ../",
    "extract:docker:apk": "docker create -ti --name sound-station-example-container sound-station-example.image /bin/bash && docker cp sound-station-example-container:/package/example/android/app/build/outputs/apk/release/app-release.apk sound-station-example.apk && docker rm -fv sound-station-example-container",
    "build:release:docker": "npm run build:docker:image && npm run extract:docker:apk"
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "metro-react-native-babel-preset": "^0.56.0"
  }
}
``
`

**Comment by drisme** [comment]
I think I figured it out. It has to do with the fact that I was symlinking the parent and that is essentially causing an endless recursion of example projects and causing metro bundler to fail. Ultimately I was getting the following error:
```
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

 Is there any work around to installing a hard copy of the dependency in example? What other options do I have to editing the directory under examples/node_modules/ ?

**Comment by brodybits** [comment]
I think the fundamental issue is that Haste and maybe the React Native build system are not all that flexible.

I would highly recommend that you just create the native library module package with the example and do `git commit` before doing any of the build customizations. This would also make it easier to apply updates based on updated templates in this package. Labeled as a **bug** since I think this really needs to be documented.
